# Generated by Django 4.0.4 on 2023-03-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap', '0005_remove_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='profile_photos/profile_user.png', upload_to='profile_photos/'),
        ),
    ]
