# Generated by Django 4.0.4 on 2023-03-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap', '0006_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('name', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=40)),
                ('photo', models.ImageField(default='profile_photos/profile_user.png', upload_to='profile_photos/')),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(default='null', max_length=50)),
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('wastetype', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='N j, Y')),
                ('typeaddress', models.CharField(max_length=20)),
                ('booking_address', models.CharField(default='null', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
