# Generated by Django 4.0.4 on 2023-03-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap', '0009_user_remove_booking_address_remove_booking_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='uid',
            new_name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
