# Generated by Django 4.0.4 on 2023-03-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap', '0016_alter_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default=21243, max_length=20),
            preserve_default=False,
        ),
    ]
