# Generated by Django 4.0.4 on 2023-03-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrap', '0017_booking_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
