# Generated by Django 4.0.4 on 2023-03-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap', '0018_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(default='User', max_length=20),
            preserve_default=False,
        ),
    ]
