# Generated by Django 4.0.4 on 2023-03-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap', '0019_user_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBin',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.IntegerField()),
                ('name', models.CharField(default='null', max_length=20)),
                ('amount', models.IntegerField()),
                ('address', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
