# Generated by Django 4.0.4 on 2023-03-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap', '0020_purchasebin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='redeem_photos/')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='purchasebin',
            name='returnsbin',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
