# Generated by Django 4.0.4 on 2023-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap', '0021_redeem_purchasebin_returnsbin'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeem',
            name='order_type',
            field=models.CharField(choices=[('one', 'Choice One'), ('two', 'Choice Two'), ('three', 'Choice Three')], default='trending', max_length=10),
            preserve_default=False,
        ),
    ]
