# Generated by Django 4.0.4 on 2023-03-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap', '0022_redeem_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.IntegerField()),
                ('name', models.CharField(default='null', max_length=20)),
                ('address_title', models.CharField(default='null', max_length=20)),
                ('address_content', models.CharField(default='null', max_length=50)),
                ('latitude', models.FloatField(default='0.0')),
                ('longitude', models.FloatField(default='0.0')),
            ],
        ),
        migrations.DeleteModel(
            name='WrapUser',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='typeaddress',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_address_title',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_latitude',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_longitude',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='redeem',
            name='order_type',
            field=models.CharField(choices=[('trending', 'trending'), ('ongoing', 'ongoing')], max_length=10),
        ),
    ]
