# Generated by Django 4.0.4 on 2023-03-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrap', '0023_addressuser_delete_wrapuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.IntegerField()),
                ('name', models.CharField(default='null', max_length=20)),
                ('photo', models.ImageField(upload_to='report_photos/')),
                ('address_report', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
